# Generated by Django 5.1.7 on 2025-04-01 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_remove_doctor_created_at_remove_doctor_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['start_time'], name='availability_start_time_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['end_time'], name='availability_end_time_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['user'], name='doctor_user_idx'),
        ),
    ]
