# Generated by Django 5.1.7 on 2025-04-01 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_created_at_and_more'),
        ('doctors', '0004_alter_availability_doctor_alter_doctor_user_and_more'),
        ('patients', '0005_alter_patient_email_alter_patient_insurance_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['datetime'], name='appointment_datetime_idx'),
        ),
    ]
