# Generated by Django 5.1.7 on 2025-04-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_doctor_alter_appointment_patient_and_more'),
        ('medical_records', '0001_initial'),
        ('patients', '0005_alter_patient_email_alter_patient_insurance_id_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient'], name='medical_record_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['appointment'], name='medical_record_appointment_idx'),
        ),
    ]
