# Generated by Django 5.1.7 on 2025-03-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insurance_id',
            field=models.BinaryField(),
        ),
    ]
